config/routes.rb
Rails.application.routes.draw do
  resources :developers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "developers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/developer.rb
class Developer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :set_developer, only: %i[ show edit update destroy ]

  # GET /developers or /developers.json
  def index
    @developers = Developer.all
  end

  # GET /developers/1 or /developers/1.json
  def show
  end

  # GET /developers/new
  def new
    @developer = Developer.new
  end

  # GET /developers/1/edit
  def edit
  end

  # POST /developers or /developers.json
  def create
    @developer = Developer.new(developer_params)

    respond_to do |format|
      if @developer.save
        format.html { redirect_to developer_url(@developer), notice: "Developer was successfully created." }
        format.json { render :show, status: :created, location: @developer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /developers/1 or /developers/1.json
  def update
    respond_to do |format|
      if @developer.update(developer_params)
        format.html { redirect_to developer_url(@developer), notice: "Developer was successfully updated." }
        format.json { render :show, status: :ok, location: @developer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /developers/1 or /developers/1.json
  def destroy
    @developer.destroy

    respond_to do |format|
      format.html { redirect_to developers_url, notice: "Developer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_developer
      @developer = Developer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def developer_params
      params.require(:developer).permit(:resume, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/views/developers/_developer.html.erb
<div id="<%= dom_id developer %>">
  <p>
    <strong>Resume:</strong>
    <%= developer.resume %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= developer.name %>
  </p>

</div>

app/views/developers/_form.html.erb
<%= form_with(model: developer) do |form| %>
  <% if developer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(developer.errors.count, "error") %> prohibited this developer from being saved:</h2>

      <ul>
        <% developer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :resume, style: "display: block" %>
    <%= form.text_area :resume %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/developers/edit.html.erb
<h1>Editing developer</h1>

<%= render "form", developer: @developer %>

<br>

<div>
  <%= link_to "Show this developer", @developer %> |
  <%= link_to "Back to developers", developers_path %>
</div>

app/views/developers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Developers</h1>

<div id="developers">
  <% @developers.each do |developer| %>
    <%= render developer %>
    <p>
      <%= link_to "Show this developer", developer %>
    </p>
  <% end %>
</div>

<%= link_to "New developer", new_developer_path %>

app/views/developers/new.html.erb
<h1>New developer</h1>

<%= render "form", developer: @developer %>

<br>

<div>
  <%= link_to "Back to developers", developers_path %>
</div>

app/views/developers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @developer %>

<div>
  <%= link_to "Edit this developer", edit_developer_path(@developer) %> |
  <%= link_to "Back to developers", developers_path %>

  <%= button_to "Destroy this developer", @developer, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dossier</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>